fix documentation typos + add output
amasad/pg-basic pull request #8
Opened 2020-04-12 03:02 UTC by MrEconomical

e

2020-04-17 22:43 UTC, MrEconomical reviewed
@amasad please review these changes!

2020-04-18 01:39 UTC, amasad requested changes
use 2 spaces not 4.

Can you also update the docs.repl.it?

2020-04-18 01:39 UTC, amasad commented on functions.js
> +      return Date.now()
use 2 spaces please

2020-04-18 18:18 UTC, MrEconomical commented on functions.js
> +      return Date.now()
fixed

2020-04-18 18:18 UTC, MrEconomical commented
synced both documentations here: https://github.com/replit/replit.github.io/pull/35
should be good now

2020-04-18 18:29 UTC, amasad commented
Thank you `e`

2020-04-18 18:29 UTC, merged